# SPDX-FileCopyrightText: Copyright (c) 2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".markdownlint-cli2.jsonc",
    "**.json",
    "**.md",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/Cargo.toml",
    "**/CNAME",
    "Cargo.lock",
    "Cargo.toml",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
